// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    AImage: typeof import('./src/components/AImage.vue')['default']
    BaseCard: typeof import('./src/components/Card/BaseCard.vue')['default']
    HelloWorld: typeof import('./src/components/HelloWorld.vue')['default']
    IconCommunity: typeof import('./src/components/icons/IconCommunity.vue')['default']
    IconDocumentation: typeof import('./src/components/icons/IconDocumentation.vue')['default']
    IconEcosystem: typeof import('./src/components/icons/IconEcosystem.vue')['default']
    IconSupport: typeof import('./src/components/icons/IconSupport.vue')['default']
    IconTooling: typeof import('./src/components/icons/IconTooling.vue')['default']
    IndexSection: typeof import('./src/components/IndexPage/IndexSection.vue')['default']
    IndexSection2: typeof import('./src/components/IndexPage/IndexSection2.vue')['default']
    NavBar: typeof import('./src/components/IndexPage/NavBar.vue')['default']
    PageLayout: typeof import('./src/components/Layout/PageLayout.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SiteHeader: typeof import('./src/components/SiteHeader.vue')['default']
    SiteLogo: typeof import('./src/components/SiteLogo.vue')['default']
    SvgIcon: typeof import('./src/components/SvgIcon.vue')['default']
    TAnchor: typeof import('tdesign-vue-next')['Anchor']
    TAnchorItem: typeof import('tdesign-vue-next')['AnchorItem']
    TAnchorTarget: typeof import('tdesign-vue-next')['AnchorTarget']
    TButton: typeof import('tdesign-vue-next')['Button']
    TCol: typeof import('tdesign-vue-next')['Col']
    TheWelcome: typeof import('./src/components/TheWelcome.vue')['default']
    TInput: typeof import('tdesign-vue-next')['Input']
    TRow: typeof import('tdesign-vue-next')['Row']
    TSpace: typeof import('tdesign-vue-next')['Space']
    TTabPanel: typeof import('tdesign-vue-next')['TabPanel']
    TTabs: typeof import('tdesign-vue-next')['Tabs']
    WelcomeItem: typeof import('./src/components/WelcomeItem.vue')['default']
  }
}
